[theme]
base = "light"
primaryColor = "#0ea5e9"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
default_mode = "Light"

[server]
headless = true
enableCORS = false
runOnSave = false

[browser]
gatherUsageStats = false

[data]
placeholder_url = "https://Woodygoodenough.github.io/finance-data-ETL/data"

